link_with 'HyperMediaAD'
platform :ios, '8.2'

# map
pod 'GoogleMaps'

# font
pod 'ionicons'

# UI
pod 'Touchpose'
pod 'BFPaperButton'
pod 'TYMActivityIndicatorView'
pod 'MTStatusBarOverlay'
pod 'FSLineChart'

# network
pod 'ISHTTPOperation'
pod 'AFNetworking'
pod 'BDBOAuth1Manager'

# calculation
pod 'SAMCubicSpline'
