#link_with 'HyperMediaAD', 'HyperMediaAD WatchKit Extension'
#use_frameworks!
link_with 'HyperMediaAD'
platform :ios, '8.2'

pod 'Mapbox-iOS-SDK', '~> 1.6.0.0'
pod 'Google-Maps-iOS-SDK'
pod 'ISHTTPOperation'
pod 'AFNetworking'
pod 'BDBOAuth1Manager'
pod 'SAMCubicSpline'
pod "FSLineChart"
pod "LFHeatMap"
